#!/bin/sh
#extended recursive search for documents - document files (doc,docx,rtf,odt)
#web: http://safrm.net/projects/efind
#author: Miroslav Safr <miroslav.safr@gmail.com> 
# needs libreoffice and unoconv
VERSION=NA                                                                   
VERSION_DATE=NA

#check dependencies
if [ ! -e "/usr/bin/unoconv" ] 
then 
    echo "Not installed unoconv, exiting.."; 
    exit 1; 
fi

WHAT=$1
SEARCH_DIR=`pwd`
if [ "x$2" != "x" ]
then
    SEARCH_DIR=$2
fi

COLORS=
if [ -x /usr/bin/tput ] && tput setaf > /dev/null; then
    COLORS=" --color=always ";
fi
FILES=$(find $SEARCH_DIR -type f -not -wholename "*\/.git*" -printf '%p\n' | grep -i -E -Z '\.(doc|docx|rtf|odt)$')

FILES_COUNT=`echo "$FILES"| grep -v '^$'  | wc -l `
echo "searching '\033[32m$WHAT\033[0m' in \033[34m$SEARCH_DIR\033[0m \033[46m$FILES_COUNT doc,docx,rtf,odt\033[0m files"

echo "${FILES}" | while IFS='\n' read -r FILE ; do
    RESULT=`unoconv  -f txt --stdout  $FILE  2> /dev/null |  grep $COLORS -E "$WHAT"`
    if [ "$RESULT" != "" ] 
    then
      echo "\033[34m$FILE\033[0m: $RESULT";
    fi
done

