#!/bin/sh
#extended recursive search for documents - combined files (html, doc, pdf, ppt, txt)
#web: http://safrm.net/projects/efind
#author: Miroslav Safr <miroslav.safr@gmail.com>
VERSION=NA
VERSION_DATE=NA

BASENAME=`basename $0`
usage() {
    echo "$BASENAME $VERSION - extended recursive search for most common data file types"
    echo " http://safrm.net/projects/efind/"
    echo "Usage:$BASENAME [OPTIONS]... PATTERN [SEARCHING_DIR]"
    echo " PATTERN ............................ string (requires \"\" if contains spaces) "
    echo " options: "
    echo " -h --help .......................... shows command line help"
    echo " -cs --case-sensitive ............... case sensitive content search (def: insensitive)"
    echo " -nf --no-filenames  ................ disable searching in filenames (def: enabled)"
    echo " -nc --no-content ................... disable searching in file content (def: enabled)"
    echo " -no --name-only .................... print only filenames (def: disabled)"
    echo " "
}

if [ "x$1" = "x--help" ]; then
    usage ; exit 0
fi

if [  $# -eq 0 ]; then
    usage ; exit 1
fi

START_TIME=`date +'%s'`

echo "TXT files=========================================="
txtfind "$@"

echo "HTML files========================================="
htmlfind "$@"

echo "PDF files=========================================="
pdffind "$@"

echo "PPT files=========================================="
pptfind "$@"

echo "DOC files=========================================="
docfind "$@"

ELAPSED_TIME=$((`date +'%s'` - $START_TIME))
echo "$BASENAME took:$(($ELAPSED_TIME/60)) min $(($ELAPSED_TIME%60)) s"
