#!/bin/sh
# extended recursive search in pdf, html, ppt files
VERSION=NA                                                                   
VERSION_DATE=NA

WHAT=$1
SEARCH_DIR=`pwd`
if [ "x$2" != "x" ]
then
    SEARCH_DIR=$2
fi
echo "==================================================="
echo "HTML files========================================="
htmlfind $1 $2

echo "==================================================="
echo "PDF files=========================================="
pdffind $1 $2

echo "==================================================="
echo "PPT files=========================================="
pptfind $1 $2

echo "==================================================="
echo "TXT files=========================================="
txtfind $1 $2
