#!/bin/sh
#extended recursive search for documents - git configs
#web: http://safrm.net/projects/efind
#author: Miroslav Safr <miroslav.safr@gmail.com> 
VERSION=NA
VERSION_DATE=NA

#support color escape characters on different terminals
alias echo="/bin/echo -e"

BASENAME=`basename $0`
usage() {
    echo "$BASENAME ${VERSION} - extended recursive search for git configs"
    echo "  http://safrm,net/projects/efind/"
    echo "Usage:$BASENAME [OPTIONS]... [PATTERN] [SEARCHING_DIR]"
    echo "  PATTERN ............... string (requires \"\" if contains spaces) "
    echo "  SEARCHING_DIR ......... root directory for searching (default: current)"
    echo "Options: "
    echo "  --help ................ shows command line help"
    echo "  -cs ................... case sensitive content search (default:insensitive)"
    echo "Note: it behaves as recursive cat if "WHAT" argument is missing"
    echo " "
}

START_TIME=`date +'%s'`
CASE_SENS=0
TOTAL_COUNT=0
FOUND_COUNT=0
FOUND_COUNT_FN=0
while [ $# -gt 0 ]; do
  case "$1" in
    --help) usage 
            exit 1
            ;;
    -cs) CASE_SENS=1 ;;
    * )
        if [ -z "$WHAT" ]; then  
            WHAT=$1 ; 
        elif [ -z "$SEARCH_DIR" ]; then
            SEARCH_DIR=$1 ;
        else
            echo "There can be only 2 arguments without <WHAT> <WHERE>, exiting.."; exit 1;        
        fi 
        ;;
  esac
  shift
done 

if [ -z "$SEARCH_DIR" ] || [ ! -e "$SEARCH_DIR" ]; then
	SEARCH_DIR="./"
fi

#check if terminal supports colors 
COLORS=
if [ -x /usr/bin/tput ] && tput setaf > /dev/null; then
    COLORS=" --color=always ";
fi
#case sensitive flag - by default ignore cases
CSF="-i "
if [ $CASE_SENS -eq 1 ]; then
    CSF="" 
fi

FIND_WHOLENAME_FLAG="-wholename"
find -wholename something --version > /dev/null 2>&1
[ $? -ne 0 ] && FIND_WHOLENAME_FLAG="-path"


#sh files first
FILES=`find $SEARCH_DIR -type f $FIND_WHOLENAME_FLAG "*\/\.git/config" -name config | grep -v '^$'`
FILES_COUNT=`echo "$FILES"  | grep -v '^$'  | wc -l `

echo "searching '\033[32m$WHAT\033[0m' in \033[01;34m$SEARCH_DIR\033[0m \033[46m$FILES_COUNT (.git/config)\033[0m files CS:$CASE_SENS"

#content search
echo "${FILES}" | \
{ while IFS='\n' read -r FILE ; do
    RESULT=`cat "$FILE" | grep $COLORS $CSF -E "$WHAT"`
    if [ "$RESULT" != "" ] 
    then
      echo "\033[01;34m$FILE\033[0m: $RESULT";
      FOUND_COUNT=$(($FOUND_COUNT + 1)) ;
    fi
  done

  ELAPSED_TIME=$((`date +'%s'` - $START_TIME))
  echo "$BASENAME found \033[42m$FOUND_COUNT from $FILES_COUNT \033[0m files, took:$(($ELAPSED_TIME/60)) min $(($ELAPSED_TIME%60)) s"
}

