#!/bin/sh
#extended recursive search for documents - html files (htm, html)
#web: http://safrm.net/projects/efind
#author: Miroslav Safr <miroslav.safr@gmail.com> 
# needs html2text
VERSION=NA                                                                   
VERSION_DATE=NA

WHAT=$1
SEARCH_DIR=`pwd`
if [ "x$2" != "x" ]
then
    SEARCH_DIR=$2
fi

COLORS=
if [ -x /usr/bin/tput ] && tput setaf > /dev/null; then
    COLORS=" --color=always ";
fi

FILES=$(find $SEARCH_DIR -type f -not -wholename "*\/.git*" -printf '%p\n' | grep -i -E -Z '\.(html|htm)$')

FILES_COUNT=`echo "$FILES" | grep -v '^$' | wc -l `

echo "searching '\033[32m$WHAT\033[0m' in \033[34m$SEARCH_DIR\033[0m \033[46m$FILES_COUNT htm,html\033[0m files"

echo "${FILES}" | while IFS='\n' read -r FILE ; do
    RESULT=`html2text "$FILE" | grep $COLORS -E "$WHAT"`
    if [ "$RESULT" != "" ]
    then
      echo "\033[34m$FILE\033[0m: $RESULT";
    fi

done

