#!/bin/sh
# recursive search in java files
VERSION=NA                                                                   
VERSION_DATE=NA

WHAT=$1
SEARCH_DIR=`pwd`
if [ "x$2" != "x" ]
then
    SEARCH_DIR=$2
fi

COLORS=
if [ `echo $TERM | grep color 1>/dev/null` ]
then
  COLORS=" --color=always ";
fi

FILES=`find $SEARCH_DIR -type f -not -wholename "*\/.git*" |grep -i "\.java\$"`
FILES_COUNT=`echo "$FILES" | wc -l `
echo "searching $WHAT in $SEARCH_DIR  $FILES_COUNT java files "
for FILE in $FILES ; do
    RESULT=`cat $FILE | grep $COLORS -E "$WHAT"`
    if [ "$RESULT" != "" ]
    then
      echo "$FILE: $RESULT";
    fi
done

