#!/bin/sh
# recursive search in pdf files 
# needs poppler-utils
VERSION=NA                                                                   
VERSION_DATE=NA

WHAT=$1
SEARCH_DIR=`pwd`
if [ "x$2" != "x" ]
then
    SEARCH_DIR=$2
fi

COLORS=
if [ -x /usr/bin/tput ] && tput setaf > /dev/null; then
    COLORS=" --color=always ";
fi

FILES=$(find $SEARCH_DIR -type f -not -wholename "*\/.git*" -printf '%p\n' | grep -i -Z "\.pdf\$")
FILES_COUNT=`echo "$FILES" | grep -v '^$' | wc -l `
echo "searching '\033[32m$WHAT\033[0m' in \033[34m$SEARCH_DIR\033[0m \033[46m$FILES_COUNT pdf\033[0m files"
echo "${FILES}" | while IFS='\n' read -r FILE ; do
    if [ -e "$FILE" ]; then
        RESULT=`pdftotext "$FILE" - | grep $COLORS -E "$WHAT"`
        if [ "$RESULT" != "" ] 
        then
          echo "\033[34m$FILE\033[0m: $RESULT";
        fi
    fi
done

