#!/bin/sh
# recursive search in txt files
VERSION=NA                                                                   
VERSION_DATE=NA

WHAT=$1
SEARCH_DIR=`pwd`
if [ "x$2" != "x" ]
then
    SEARCH_DIR=$2
fi

COLORS=
if [ -x /usr/bin/tput ] && tput setaf > /dev/null ; then
    COLORS=" --color=always ";
fi

FILES=`find $SEARCH_DIR -type f -not -wholename "*\/.git*" |grep -i "\.txt\$"`
FILES_COUNT=`echo "$FILES" | wc -l `
echo "searching '\033[32m$WHAT\033[0m' in \033[34m$SEARCH_DIR\033[0m \033[46m$FILES_COUNT txt\033[0m files"
for FILE in $FILES ; do
    RESULT=`cat $FILE | grep $COLORS -E "$WHAT"`
    if [ "$RESULT" != "" ]
    then
      echo "\033[34m$FILE\033[0m: $RESULT";
    fi
done

