#!/bin/sh
#extended recursive search for documents - xml files (xml)
#web: http://safrm.net/projects/efind
#author: Miroslav Safr <miroslav.safr@gmail.com> 
VERSION=NA                                                                   
VERSION_DATE=NA

#check dependencies xml2 package
if [ ! -e "/usr/bin/xml2" ] 
then 
    echo "Not installed xml2, exiting.."; 
    exit 1; 
fi

WHAT=$1
SEARCH_DIR=`pwd`
if [ "x$2" != "x" ]
then
    SEARCH_DIR=$2
fi

COLORS=
if [ -x /usr/bin/tput ] && tput setaf > /dev/null; then
    COLORS=" --color=always ";
fi

FILES=`find $SEARCH_DIR -type f -not -wholename "*\/.git*" |grep -i "\.xml\$"`
FILES_COUNT=`echo "$FILES"| grep -v '^$'  | wc -l`
echo "searching '\033[32m$WHAT\033[0m' in \033[34m$SEARCH_DIR\033[0m \033[46m$FILES_COUNT xml\033[0m files"
for FILE in $FILES ; do
    RESULT=`xml2 < "$FILE" |  grep $COLORS -E "$WHAT"`
    if [ "$RESULT" != "" ] 
    then
      echo "\033[34m$FILE\033[0m: $RESULT";
    fi
done
