#!/bin/sh
# recursive search in xml 
VERSION=NA                                                                   
VERSION_DATE=NA

#check dependencies xml2 package
if [ ! -e "/usr/bin/xml2" ] 
then 
    echo "Not installed xml2, exiting.."; 
    exit 1; 
fi

WHAT=$1
SEARCH_DIR=`pwd`
if [ "x$2" != "x" ]
then
    SEARCH_DIR=$2
fi

COLORS=
if [ -x /usr/bin/tput ] && tput setaf > /dev/null; then
    COLORS=" --color=always ";
fi

FILES=`find $SEARCH_DIR -type f -not -wholename "*\/.git*" |grep -i "\.xml\$"`
FILES_COUNT=`echo "$FILES" | wc -l `
echo "searching '$WHAT' in $SEARCH_DIR  $FILES_COUNT xml files "
for FILE in $FILES ; do
    RESULT=`xml2 < $FILE |  grep $COLORS -E "$WHAT"`
    if [ "$RESULT" != "" ] 
    then
      echo "$FILE: $RESULT";
    fi
done
